version = "0.1-beta"
available_importers = ["cv.CVImporter", "vimba.VimbaImporter"]
chosen_importer = "cv.CVImporter"
eyeloop = 0
engine = 0
arguments = 0
file_manager = 0
graphical_user_interface = 0
